networks:
  web:
    name: web
  intercom:
    name: intercom

volumes:
  order_pg_vol:

services:

  traefik:
    image: "traefik:v3.5.2"
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --api.insecure=true
    ports:
      - "80:80"       # per localhost i orders.localhost
      - "8080:8080"   # dashboard (opcional)
    volumes:
      # si uses Docker Desktop (WSL2), aquesta ruta funciona
      - /var/run/docker.sock:/var/run/docker.sock:ro

      # si falla en Windows, substitueix per:
      # - type: npipe
      #   source: \\.\pipe\docker_engine
      #   target: /var/run/docker.sock

    networks:
      - web


  orderservice:
    container_name: orderservice
    build: .
    command: [ "/app/ordersystem" ]
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_TCP_PORT=5432
      - DB_HOST=order-postgres
    networks:
      - intercom
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orderservice.rule=Host(`orders.localhost`)"
      - "traefik.http.routers.orderservice.entrypoints=web"
      - "traefik.http.services.orderservice.loadbalancer.server.port=3000"


  sws:
    image: joseluisq/static-web-server:latest
    container_name: sws
    environment:
      - SERVER_ROOT=/public
      - SERVER_PORT=80
    volumes:
      - ./frontend:/public:ro
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sws.rule=Host(`localhost`)"
      - "traefik.http.routers.sws.entrypoints=web"
      - "traefik.http.services.sws.loadbalancer.server.port=80"


  order-postgres:
    image: postgres:latest
    restart: always
    networks:
      - intercom
    volumes:
      - order_pg_vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_TCP_PORT=5432
